import { classifyAnchorPath } from "../taxonomy.js";
import type { Validator } from "./types.js";
import { maybeMigrationBlock, violation } from "./types.js";

export const validateDirectoryTaxonomy: Validator = (context) => {
  const classification = classifyAnchorPath(context.name);

  if (classification.kind === "generated") {
    return [
      violation(
        "BLOCK",
        "generated_file_reserved",
        "CONTEXT-ROOT.md is generated by writeContextRoot and cannot be written through writeAnchor.",
        context.repoRelativePath,
      ),
    ];
  }

  if (classification.kind === "invalid") {
    return [maybeMigrationBlock(context, "directory_taxonomy", classification.reason)];
  }

  return [];
};

