import type { AnchorMeta, ContextRootEntry, ContextRootFormat, ContextRootResult } from "./types.js";
import { ANCHOR_CATEGORIES, categoryTitle } from "./taxonomy.js";

export function buildContextRoot(
  anchors: AnchorMeta[],
  options: {
    generatedAt?: string;
    format?: ContextRootFormat;
  } = {},
): ContextRootResult {
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const entries = anchors.map(toContextRootEntry).sort(compareContextEntries);
  const format = options.format ?? "both";

  return {
    generatedAt,
    entries,
    markdown: format === "json" ? undefined : renderContextRootMarkdown(entries, generatedAt),
  };
}

export function renderContextRootMarkdown(entries: ContextRootEntry[], generatedAt: string): string {
  const lines = [
    "# CONTEXT-ROOT",
    "",
    "> Generated by anchor-mcp from anchor front matter. Do not edit manually; update anchors and regenerate.",
    "",
    `Generated: ${generatedAt}`,
    "",
  ];

  for (const category of ANCHOR_CATEGORIES) {
    const group = entries.filter((entry) => entry.category === category);
    if (group.length === 0) {
      continue;
    }

    lines.push(`## ${categoryTitle(category)}`, "");
    for (const entry of group) {
      const label = entry.title || entry.name;
      lines.push(`### [${escapeMarkdown(label)}](${entry.path})`);
      lines.push("");
      lines.push(entry.summary);
      lines.push("");
      lines.push("Read this if:");
      for (const instruction of entry.read_this_if) {
        lines.push(`- ${instruction}`);
      }
      lines.push("");
      lines.push(`Metadata: \`${entry.type}\`${entry.projectSlug ? `, project \`${entry.projectSlug}\`` : ""}`);
      lines.push("");
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function toContextRootEntry(anchor: AnchorMeta): ContextRootEntry {
  return {
    name: anchor.name,
    path: anchor.path,
    title: anchor.title,
    category: anchor.category,
    projectSlug: anchor.projectSlug,
    summary: anchor.summary,
    read_this_if: anchor.read_this_if,
    type: anchor.type,
    tags: anchor.tags,
    project: anchor.project,
    last_validated: anchor.last_validated,
  };
}

function compareContextEntries(left: ContextRootEntry, right: ContextRootEntry): number {
  const categoryDelta = ANCHOR_CATEGORIES.indexOf(left.category) - ANCHOR_CATEGORIES.indexOf(right.category);
  if (categoryDelta !== 0) {
    return categoryDelta;
  }

  const leftProject = left.projectSlug ?? "";
  const rightProject = right.projectSlug ?? "";
  if (leftProject !== rightProject) {
    return leftProject.localeCompare(rightProject);
  }

  return left.name.localeCompare(right.name);
}

function escapeMarkdown(input: string): string {
  return input.replaceAll("[", "\\[").replaceAll("]", "\\]");
}

