import type { AnchorMeta, ContextRootEntry, ContextRootFormat, ContextRootResult } from "./types.js";
import { ANCHOR_CATEGORIES, discoveryCategoryIndex, discoveryCategoryTitle } from "./taxonomy.js";

export function buildContextRoot(
  anchors: AnchorMeta[],
  options: {
    generatedAt?: string;
    format?: ContextRootFormat;
  } = {},
): ContextRootResult {
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const entries = anchors.map(toContextRootEntry).sort(compareContextEntries);
  const format = options.format ?? "both";

  return {
    generatedAt,
    entries,
    markdown: format === "json" ? undefined : renderContextRootMarkdown(entries, generatedAt),
  };
}

export function renderContextRootMarkdown(entries: ContextRootEntry[], generatedAt: string): string {
  const lines = [
    "# CONTEXT-ROOT",
    "",
    "> Generated by anchor-mcp from anchor front matter. Do not edit manually; update anchors and regenerate.",
    "",
    `Generated: ${generatedAt}`,
    "",
  ];

  const builtIn = entries.filter((entry) => entry.origin === "built-in");
  const repoEntries = entries.filter((entry) => entry.origin !== "built-in");

  if (builtIn.length > 0) {
    lines.push("## Built-in server policy — not in git", "");
    for (const entry of builtIn) {
      lines.push(...renderContextRootEntryBlock(entry));
    }
  }

  for (const category of ANCHOR_CATEGORIES) {
    const group = repoEntries.filter((entry) => entry.category === category);
    if (group.length === 0) {
      continue;
    }

    lines.push(`## ${discoveryCategoryTitle(category)}`, "");
    if (category === "projects") {
      lines.push(...renderProjectsSection(group));
    } else {
      for (const entry of group) {
        lines.push(...renderContextRootEntryBlock(entry));
      }
    }
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function renderProjectsSection(entries: ContextRootEntry[]): string[] {
  const hasMilestone = entries.some((entry) => entry.name.includes("/milestones/"));
  if (!hasMilestone) {
    return entries.flatMap((entry) => renderContextRootEntryBlock(entry));
  }

  const bySlug = new Map<string, ContextRootEntry[]>();
  for (const entry of entries) {
    const slug = entry.projectSlug ?? "__none__";
    if (!bySlug.has(slug)) {
      bySlug.set(slug, []);
    }
    bySlug.get(slug)!.push(entry);
  }

  const lines: string[] = [];
  for (const slug of [...bySlug.keys()].sort()) {
    const list = bySlug.get(slug) ?? [];
    const milestones = list.filter((e) => e.name.includes("/milestones/")).sort((a, b) => a.name.localeCompare(b.name));
    const others = list.filter((e) => !e.name.includes("/milestones/")).sort((a, b) => a.name.localeCompare(b.name));

    if (slug !== "__none__") {
      lines.push(`### Project \`${slug}\``, "");
    }

    if (milestones.length > 0) {
      lines.push("#### Milestones", "");
      for (const m of milestones) {
        const label = m.title || m.name;
        const st = m.milestoneStatus ?? "unknown";
        lines.push(`- [${escapeMarkdown(label)}](${m.path}) — **${escapeMarkdown(st)}** — ${escapeMarkdown(m.summary)}`);
      }
      lines.push("");
    }

    for (const entry of others) {
      lines.push(...renderContextRootEntryBlock(entry));
    }
  }

  return lines;
}

function renderContextRootEntryBlock(entry: ContextRootEntry): string[] {
  const out: string[] = [];
  const label = entry.title || entry.name;
  out.push(`### [${escapeMarkdown(label)}](${entry.path})`, "");
  out.push(entry.summary);
  out.push("");
  out.push("Read this if:");
  for (const instruction of entry.read_this_if) {
    out.push(`- ${instruction}`);
  }
  out.push("");
  const metaBits = [`\`${entry.type}\``];
  if (entry.projectSlug) {
    metaBits.push(`project \`${entry.projectSlug}\``);
  }
  if (entry.policyVersion) {
    metaBits.push(`policy \`${entry.policyVersion}\``);
  }
  out.push(`Metadata: ${metaBits.join(", ")}`);
  if (entry.acceptanceCriteria) {
    const ac = entry.acceptanceCriteria;
    out.push("");
    out.push(
      `Acceptance criteria: ${ac.goalsWithCriteria}/${ac.activeGoals} goals with criteria; missing: ${ac.goalsMissingCriteria.length ? ac.goalsMissingCriteria.join("; ") : "none"}; proposed: ${ac.hasProposedCriteria ? "yes" : "no"}.`,
    );
  }
  out.push("");
  return out;
}

function toContextRootEntry(anchor: AnchorMeta): ContextRootEntry {
  return {
    name: anchor.name,
    path: anchor.path,
    title: anchor.title,
    category: anchor.category,
    projectSlug: anchor.projectSlug,
    summary: anchor.summary,
    read_this_if: anchor.read_this_if,
    type: anchor.type,
    tags: anchor.tags,
    project: anchor.project,
    last_validated: anchor.last_validated,
    origin: anchor.origin,
    policyVersion: anchor.policyVersion,
    acceptanceCriteria: anchor.acceptanceCriteria,
    milestoneStatus: anchor.milestone?.status,
  };
}

function compareContextEntries(left: ContextRootEntry, right: ContextRootEntry): number {
  const categoryDelta = discoveryCategoryIndex(left.category) - discoveryCategoryIndex(right.category);
  if (categoryDelta !== 0) {
    return categoryDelta;
  }

  const leftProject = left.projectSlug ?? "";
  const rightProject = right.projectSlug ?? "";
  if (leftProject !== rightProject) {
    return leftProject.localeCompare(rightProject);
  }

  return left.name.localeCompare(right.name);
}

function escapeMarkdown(input: string): string {
  return input.replaceAll("[", "\\[").replaceAll("]", "\\]");
}

